from __future__ import annotations

from typing import Protocol

from app.domain.entities.user import User, UserRole


class UserRepository(Protocol):
    def get_by_email(self, email: str) -> User | None: ...

    def get_by_id(self, user_id: str) -> User | None: ...

    def list(self) -> list[User]: ...

    def create(self, user: User) -> User: ...

    def update(self, user: User) -> User: ...

    def email_exists(self, email: str, exclude_user_id: str | None = None) -> bool: ...

    def has_role(self, role: UserRole) -> bool: ...
